### ISSUE TITLE
Improvement DevRoadmaps

### ISSUE THREAD

**Issue by chez14** [chez14/node-myanimelist-url-to-id#2]
- [x] Github Actions Test using Jest.
- [x] More verbose documentation on how to use it.
- [x] Update to use @repurika's credential to publish things.
- [x] Remove ts-node.
- [x] After all of that, Release a majot version for this.

**Comment by repurika** [comment]
:rocket: Issue was released in [`v1.0.0`](https://github.com/chez14/node-myanimelist-url-to-id/releases/tag/v1.0.0) :rocket:
